"""
Django settings for modern_electricos project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&0$5i)t-f(jb)soq^j(_o0=)g=$u5z6gfp7y%rdd^c#nnb8kt3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.postgres',

# =====    CUSTOM APPS =======

    "home",
    "enquiry",
    'csp',
]




#APP_INSTANCE_ID = "f2833737-7b61-48db-b1fe-e3e63f92313a"   # "b6e7dc4d-9f10-4bbf-ad6c-38f0c9a541ce"
APP_INSTANCE_ID                =  "b6e7dc4d-9f10-4bbf-ad6c-38f0c9a541ce"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = "modern_electricos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = "modern_electricos.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'modern_electricos',
        'USER': 'postgres',
        'PASSWORD': '12345',
        'HOST': 'localhost',       # ya '127.0.0.1' agar local hai
        'PORT': '5432',            # default PostgreSQL port
        # Optional: performance ke liye
        'CONN_MAX_AGE': 600,       # 10 min connection pooling
        'OPTIONS': {
            'sslmode': 'prefer',   # agar SSL chahiye to 'require' kar dena
        },
}
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"




MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


TIME_ZONE = 'Asia/Kolkata'   # ya apni choice
USE_TZ = True



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}




SECURE_CONTENT_TYPE_NOSNIFF = True





SECURE_HSTS_SECONDS = 31536000
SECURE_SSL_REDIRECT = False



# CSRF_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = False



SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"









# Only allow JS from your domain
#CSP_SCRIPT_SRC = ("'self'",)

# Optional: Inline scripts allow karne ke liye (safer: use nonce)
#CSP_STYLE_SRC = ("'self'",)  # CSS bhi control hota hai


#CSP_SCRIPT_SRC = ("'self'", "'nonce-<random-nonce>'")



# CSP_SCRIPT_SRC = (
#     "'self'",
#     "https://cdn.jsdelivr.net",
#     "https://cdnjs.cloudflare.com"
# )





SECURE_HSTS_SECONDS = 31536000
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True