# Generated by Django 5.2.5 on 2026-02-13 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                ("service_required", models.JSONField()),
                ("project_details", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=10,
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under500", "Under 500"),
                            ("500-1000", "500 - 1000"),
                            ("1000-5000", "1000 - 5000"),
                            ("5000-10000", "5000 - 10000"),
                            ("over10000", "Over 10000"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.TextField(blank=True, null=True)),
                ("request_hash", models.CharField(db_index=True, max_length=64)),
                ("instance_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="enquiry_enq_email_757980_idx",
                    ),
                    models.Index(
                        fields=["phone", "created_at"],
                        name="enquiry_enq_phone_efdd8e_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_processed"],
                        name="enquiry_enq_priorit_f50807_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_hash",), name="unique_request_hash"
                    )
                ],
            },
        ),
    ]
