# Generated by Django 5.2.5 on 2026-02-12 17:13

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="PowerPro Electrical",
                        help_text="Company title - CharField",
                        max_length=200,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Professional Electrical Solutions",
                        help_text="Company tagline - CharField",
                        max_length=200,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        default="1-800-555-3782",
                        help_text="Contact number - CharField",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@powerproelectrical.com",
                        help_text="Email address - EmailField",
                        max_length=100,
                    ),
                ),
                (
                    "reviews_and_count",
                    models.CharField(
                        default="4.8/5 (247 reviews)",
                        help_text="Reviews text - CharField",
                        max_length=50,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Licensed & insured electrical services with 24/7 emergency support. Serving residential and commercial clients since 2005.",
                        help_text="Hero subtitle - CharField",
                        max_length=500,
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True, help_text="About company - TextField", null=True
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, help_text="Footer text - TextField", null=True
                    ),
                ),
                (
                    "project_complete_count",
                    models.IntegerField(
                        default=2473,
                        help_text="Projects completed count - IntegerField",
                    ),
                ),
                (
                    "service_years",
                    models.PositiveIntegerField(
                        default=18, help_text="Years of service - PositiveIntegerField"
                    ),
                ),
                (
                    "employees_count",
                    models.SmallIntegerField(
                        default=50, help_text="Number of employees - SmallIntegerField"
                    ),
                ),
                (
                    "office_locations",
                    models.BigIntegerField(
                        default=5,
                        help_text="Number of office locations - BigIntegerField",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.8,
                        help_text="Average rating - DecimalField",
                        max_digits=3,
                    ),
                ),
                (
                    "satisfaction_rate",
                    models.FloatField(
                        default=98.5,
                        help_text="Customer satisfaction rate - FloatField",
                    ),
                ),
                (
                    "show_ad_section",
                    models.BooleanField(
                        default=True, help_text="Show/hide ad section - BooleanField"
                    ),
                ),
                (
                    "is_emergency_available",
                    models.BooleanField(
                        default=True,
                        help_text="Emergency service available - BooleanField",
                    ),
                ),
                (
                    "is_licensed",
                    models.BooleanField(
                        default=True, help_text="Company licensed - BooleanField"
                    ),
                ),
                (
                    "is_insured",
                    models.BooleanField(
                        default=True, help_text="Company insured - BooleanField"
                    ),
                ),
                (
                    "founded_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Company founded date - DateField",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last updated timestamp - DateTimeField",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created timestamp - DateTimeField"
                    ),
                ),
                (
                    "company_info",
                    models.JSONField(
                        default=dict, help_text="Company info as JSONB - JSONField"
                    ),
                ),
                (
                    "seo_settings",
                    models.JSONField(
                        default=dict, help_text="SEO settings as JSONB - JSONField"
                    ),
                ),
                (
                    "theme_settings",
                    models.JSONField(
                        default=dict, help_text="Theme colors as JSONB - JSONField"
                    ),
                ),
                ("ads", models.JSONField(blank=True, default=list)),
                ("services_data", models.JSONField(blank=True, default=list)),
                (
                    "business_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Business hours array - ArrayField of CharField",
                        size=None,
                    ),
                ),
                (
                    "certifications",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Certifications array - ArrayField",
                        size=None,
                    ),
                ),
                (
                    "payment_methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="Payment methods array - ArrayField",
                        size=None,
                    ),
                ),
                (
                    "service_areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Service areas array - ArrayField",
                        size=None,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Key-value metadata - JSONB"
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics key-value - JSONB",
                    ),
                ),
                (
                    "active_period",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True,
                        help_text="Active date range - DateRangeField",
                        null=True,
                    ),
                ),
                (
                    "support_hours",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True,
                        help_text="Support hours range - DateTimeRangeField",
                        null=True,
                    ),
                ),
                (
                    "employee_count_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True,
                        help_text="Employee count range - IntegerRangeField",
                        null=True,
                    ),
                ),
                (
                    "budget_range",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True,
                        help_text="Budget range - DecimalRangeField",
                        null=True,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        default="https://www.powerproelectrical.com",
                        help_text="Website URL - URLField",
                        max_length=500,
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, help_text="Facebook URL - URLField", max_length=500
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Instagram URL - URLField", max_length=500
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn URL - URLField", max_length=500
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo - ImageField",
                        null=True,
                        upload_to="logos/",
                    ),
                ),
                (
                    "favicon",
                    models.FileField(
                        blank=True,
                        help_text="Favicon - FileField",
                        null=True,
                        upload_to="favicon/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="powerpro-electrical",
                        help_text="URL slug - SlugField",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "last_modified_by_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Last modified by IP - GenericIPAddressField",
                        null=True,
                    ),
                ),
                (
                    "instance_version",
                    models.BigIntegerField(
                        default=1,
                        help_text="Instance version - BigIntegerField",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Instance",
                "verbose_name_plural": "App Instances",
                "db_table": "app_instance",
                "indexes": [
                    models.Index(
                        fields=["title", "slug"], name="app_instanc_title_2e6271_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="app_instanc_created_dbb256_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["company_info"], name="app_instanc_company_af596f_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["seo_settings"], name="app_instanc_seo_set_5e4348_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["theme_settings"], name="app_instanc_theme_s_cb641c_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["metadata"], name="metadata_gin_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["statistics"], name="app_instanc_statist_5eb3b4_gin"
                    ),
                ],
            },
        ),
    ]
