# Generated by Django 5.2.5 on 2026-02-14 06:29

import django.contrib.postgres.search
import home.addressType
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="address",
            field=home.addressType.AddressField(
                help_text="Composite address_type field", null=True
            ),
        ),
        migrations.AddField(
            model_name="appinstance",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
