# Generated by Django 5.2.5 on 2026-02-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_appinstance_address_appinstance_search_vector"),
    ]

    operations = []
